---
deployment:
  tasks:
    - export DEPLOYPATH=/home/u7010320/public_html/andreherwanto/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp -css $DEPLOYPATH
      /bin/cp -Vd $DEPLOYPATH
      /bin/cp -img $DEPLOYPATH
